### ISSUE TITLE
Tracking Issue: Non-implemented tests

### ISSUE THREAD

**Issue by sadlerap** [servicebinding/conformance#18]
There's still a lot of tests not yet implemented in the conformance test suite.  This issue aims to track outstanding missing tests.

Service Binding tests:
 - [ ] Binding workloads with a label selector (PR: #16)
 - [ ] `ClusterWorkloadResourceMapping.servicebinding.io` resource tests
 - [ ] Projecting environment variables
 - [ ] Binding only named containers
 - [ ] Status handling for failed bindings

Service tests:
 - [ ] Validate existence of `.status.binding.name`
 - [ ] Validate `.status.binding.name` points at a valid secret
